# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://drvan.dev/"
DefaultContentLanguage  = "en"
title                   = "Ryan Van Antwerp"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = "UA-172330175-1"
pluralizeListTitles     = false
disableLanguages        = [""]

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "email"]

  [params.meta]
    description         = "Ryan Van Antwerp's portfolio and blog."
    author              = "Ryan Van Antwerp"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Ryan Van Antwerp"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "Ryan Van Antwerp, Ph.D."
    paragraph             = "Full Stack Developer, Security Solutions Engineer, Father, Runner"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.jpg"
      shape               = "circle"
      width               = "80"
      alt                 = "Ryan Van Antwerp"

  [params.sidebar]
    about               = """
    Hi! I'm Ryan - I'm a full stack developer and security solutions engineer with 8 years of experience solving 
    challenging technical problems and building robust and innovative software. I currently work for Comcast as 
    a Principal Security Engineer. I also teach Reverse Engineering and Exploitation as part of the University 
    of Delaware's Cybersecurity graduate program.
    """
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  # Coding Communities
  github                = "drvan"
  # gitlab                = ""
  # stackoverflow         = "" # User Number
  # bitbucket             = ""
  # jsfiddle              = ""
  # codepen               = ""
  # # Visual Art Communities
  # deviantart            = ""
  # flickr                = "example"
  # behance               = ""
  # dribbble              = ""
  # # Publishing Communities
  # wordpress             = ""
  # medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "ryan-van-antwerp-75441669"
  # linkedin_company      = "examplebusiness"
  # foursquare            = ""
  # xing                  = ""
  # slideshare            = ""
  # Social Networks
  # facebook              = "example"
  # googleplus            = ""
  # reddit                = "example"
  # quora                 = ""
  # youtube               = ""
  # vimeo                 = ""
  # whatsapp              = "" # WhatsApp Number
  #   # WeChat and QQ need testing.
  #   wechat              = ""
  #   qq                  = "" # User ID Number
  # instagram             = "example"
  # tumblr                = ""
  # twitter               = "example"
  strava                = "46901649"
  # skype                 = ""
  # snapchat              = ""
  # pinterest             = "example"
  # telegram              = "example"
  # vine                  = ""
  googlescholar         = "zRGxukkAAAAJ"
  # orcid                 = ""
  # researchgate          = "example"
  # keybase               = "example"
  # mastodon              = "example.com/@example"
  # Email
  email                 = "rvanantwerp AT gmail.com"